spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com:3306/heroku_a7b07a84e6aeb78
    username: b8fe6ab1166bac
    password: 7ec3f3b6
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      ddl-auto: update
    show-sql: true

server:
  port: 9000